[package]
name = "c"
version = "0.1.0"
authors = ["Julian Orth <ju.orth@gmail.com>", "Alex Chandel <alexchandel@gmail.com>", "David Wood <devel@dtwood.uk>"]
build = true

[dependencies]
libc = "*"
syscall = "*"
rlibc = "*"

[build-dependencies]
gcc = "*"
